import { TextEdit, Button } from "std-widgets.slint";

export component InputFieldGeneric inherits Window 
{
    in property <string> name;
    in property <string> default-text;

    in property <int> guess-button-id;
    in property <int> show-button-id;
    
    in-out property <string> edited_string;

    callback button_id(int);
    

    width: 470px;
    height: 90px;

    background: transparent;

    Text 
    {
        x: 10px;
        y: 5px;

        font-size: 25px;
        font-weight: 600;
        
        vertical-alignment: bottom;
        
        text: name;
    }

    TextEdit 
    {
        x: 10px;
        y: 35px;

        width: 200px;
        height: 38px;
        
        placeholder-text: default-text;

        text <=> edited_string;

        key-pressed(event) => 
        {
            if (event.text == Key.Backspace ||
                event.text == Key.LeftArrow ||
                event.text == Key.RightArrow) 
            {
                return reject; 
            }

            if ((event.text >= "0" && event.text <= "9") ||
                event.text == "." || event.text == "/")
            {
                return reject; 
            }

            accept;
        }
    }
    
    Button 
    {
        x: 235px;
        y: 35px;

        width: 100px;
        height: 38px;

        text: "Check Guess";

        clicked => 
        {
            root.button_id(guess-button-id);
        };
    }

    Button 
    {
        x: 360px;
        y: 35px;

        width: 100px;
        height: 38px;

        text: "Show Answer";

        clicked => 
        {
            root.button_id(show-button-id);
        };
    }
} 
