import { LineEdit, Button } from "std-widgets.slint";
export component InputFieldGeneric inherits Window
{
    in property <string> name;
    in property <string> default-text;

    in property <int> guess-button-id;
    in property <int> show-button-id;

    callback button-output(string, int);

    width: 470px;
    height: 90px;

    Rectangle 
    {
        x: 0px;
        y: 0px; 
        
        background: black;

        Text 
        {
            x: 10px;
            y: 5px;

            font-size: 25px;
            font-weight: 600;
            
            vertical-alignment: bottom;
            
            text: name;
        }
        
        line-edit := LineEdit 
        {
            x: 10px;
            y: 35px;

            width: 200px;
            height: 35px;
            
            placeholder-text: default-text;
        }
        
        Button 
        {
            x: 235px;
            y: 35px;

            width: 100px;
            height: 35px;

            text: "Check Guess";

            clicked => 
            {
                root.button-output(line-edit.text, guess-button-id);
                debug(line-edit.text + ", " + guess-button-id);
            };
        }

        Button 
        {
            x: 360px;
            y: 35px;

            width: 100px;
            height: 35px;

            text: "Show Answer";

            clicked => 
            {
                root.button-output(line-edit.text, show-button-id);
                debug(line-edit.text + ", " + guess-button-id);
            };
        }
    } 
}